version: "3"

services:
  django:
    build:
      context: .
    container_name: gol-htmx-django
    volumes:
      - ./src:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: python manage.py runserver_plus --reloader-interval=5 0.0.0.0:8000
