[tool.pip-tools]
generate-hashes = true
strip-extras = true

[tool.ruff]
target-version = "py312"
line-length = 120
include = ["pyproject.toml", "src/**/*.py"]
exclude = ["src/**/migrations"]

[tool.ruff.lint]
preview = true
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-bandit
    "S",
    # flake8-logging
    "LOG",
    # flake8-comprehensions
    "C4",
    # flake8-print
    "T20",
    # flake8-pytest-style
    "PT",
    # isort
    "I",
    # Pylint
    "PL",
    # Ruff-specific rules
    "RUF",
]
unfixable = ["B"]
ignore = ["S101", "PLR2004"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"src/manage.py" = ["PLC0415"]

[tool.ruff.lint.isort]
known-first-party = ["apps"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "django",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]

[tool.ruff.format]
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 79

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
exclude = ["src/**/migrations"]
include = ["src"]
